### ISSUE TITLE
Cannot generate

### ISSUE THREAD

**Issue by seongbae** [kejojedi/crudify#1]
When I run the generate command, it gives error:

seongbae@daegu:~/projects/laravel7$ php artisan crudify:generate Car
Created new file: /home/seongbae/projects/laravel7/app/Car.php

   ErrorException 

  file_put_contents(/home/seongbae/projects/laravel7/app/Http\Controllers/CarController.php): failed to open stream: No such file or directory

  at vendor/kejojedi/crudify/src/Commands/GeneratesCrud.php:85
    81| 
    82|     private function createFile($new_file, $stub_contents)
    83|     {
    84|         if (!file_exists($new_file) || $this->option('force')) {
  > 85|             file_put_contents($new_file, $this->replace($stub_contents));
    86| 
    87|             $this->line('Created new file: ' . $new_file);
    88|         }
    89|         else {

      +17 vendor frames 
  18  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by kejojedi** [comment]
Are you on Windows, Linux, or Mac?

Looks like a permissions issue. Please let me know what OS so I can come up with a solution.

**Comment by kejojedi** [comment]
I figured it out. I was using a backslash instead of a forward slash in the generator (which is weird because it worked on my OS).

Please run `composer update` to update to `1.1.3`, it should work now.

**Comment by seongbae** [comment]
Got it. Thanks!

Am using Ubuntu.
