### ISSUE TITLE
How to add dynamic fields to datatable?

### ISSUE THREAD

**Issue by seongbae** [kejojedi/crudify#3]
When I use yajra's datatable, I can add dynamic fields by doing following:

`public function dataTable($query)
    {
        return datatables()
            ->eloquent($query)
             ->addColumn('img', function($row) {
                return '<img src="/storage/media/'. $row->path .'" class="img-fluid" style="width:80px;">';
            })
            ->escapeColumns([]);
    }`

How do I do that with your datatable class?

**Comment by redbastie** [comment]
Check the readme for the jsonMethods method. It explains how to do it with that method in your table class.

**Comment by seongbae** [comment]
doh!  thank you!!
